[package]
name = "storm-engine"
version = "0.1.0"
edition = "2024"
license-file = "LICENSE"
description = "A rules engien for MTG"
repository = "https://github.com/andraaal/storm"
readme = "README.md"
exclude = ["random TODOs.md"]

[dependencies]
slotmap = "1.1"
flagset = "0.4"
thiserror = "2.0"
derive_more = {version = "2.1", features = ["from", "try_into"]}
